apiVersion: v1
kind: PersistentVolume
metadata:
  name: openam-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/openam
  persistentVolumeReclaimPolicy: Retain
